// Copyright 2026 Phinomenon Inc.
//
// Use of this source code is governed by an Apache license that can be
// found in the LICENSE file.

#import "PhiApplication.h"
#import "PhiLogging.h"
#import <Carbon/Carbon.h>
#import <Cocoa/Cocoa.h>
@interface PhiApplication ()
@property(nonatomic, assign) BOOL handlingSendEvent;
@end

#define DEBUG_EVENT 0
@implementation PhiApplication

- (void)sendEvent:(NSEvent *)event {
#if DEBUG_EVENT
    NSLog(@"sending event: %@", [self descriptionForNSEvent:event]);
#endif

    // Handle swipe events generated by devices that emulate back/forward gestures.
    if (event.type == NSEventTypeSwipe) {
        CGFloat dx = event.deltaX;
        if (dx > 0.0) {
            AppLogDebug(@"Swipe detected → Back (dx=%f)", dx);
            [NSApp sendAction:@selector(goBack:) to:nil from:self];
            return;
        } else if (dx < 0.0) {
            AppLogDebug(@"Swipe detected → Forward (dx=%f)", dx);
            [NSApp sendAction:@selector(goForward:) to:nil from:self];
            return;
        }
    }
  
    
    if (event.type == NSEventTypeKeyDown &&
        (event.keyCode == kVK_JIS_Eisu || event.keyCode == kVK_JIS_Kana)) {
        [NSApp.keyWindow sendEvent:event];
    } else {
        [super sendEvent:event];
    }
}

- (BOOL)isHandlingSendEvent {
    return _handlingSendEvent;
}

- (void)setHandlingSendEvent:(BOOL)handlingSendEvent {
    _handlingSendEvent = handlingSendEvent;
    AppLogDebug(@"setHandlingSendEvent: %d", handlingSendEvent);
}

- (void)terminate:(id)sender {
    if ([[ChromiumLauncher sharedInstance].bridge respondsToSelector:@selector(tryToTerminateApplication:)]) {
        [[ChromiumLauncher sharedInstance].bridge tryToTerminateApplication:self];
    }
   
}

- (void)cancelTerminate:(id)sender {
    if ( [[ChromiumLauncher sharedInstance].bridge respondsToSelector:@selector(stopTryingToTerminateApplication:)]) {
        [[ChromiumLauncher sharedInstance].bridge stopTryingToTerminateApplication:self];
    }
}

- (NSString *)descriptionForNSEvent:(NSEvent *)event {
    NSMutableString *desc = [NSMutableString
        stringWithFormat:
            @"NSEvent type=%ld modifierFlags=0x%lx locationInWindow=(%g,%g)",
            event.type, event.modifierFlags, event.locationInWindow.x,
            event.locationInWindow.y];

    switch (event.type) {
    case NSEventTypeKeyDown:
    case NSEventTypeKeyUp: {
        // Some NSEvents return a string with NUL in
        // event.characters, see
        // <https://crbug.com/826908>. To make matters
        // worse, in rare cases,
        // NSEvent.characters or
        // NSEvent.charactersIgnoringModifiers can throw an
        // NSException complaining that
        //"TSMProcessRawKeyCode failed". Since we're
        // trying to gather a crash key here, if that
        // exception happens, just
        // remark that it happened and continue rather
        // than crashing the browser.
        NSString *characters, *unmodifiedCharacters;
        @try {
            characters = [event.characters
                stringByReplacingOccurrencesOfString:@"\0"
                                          withString:@"\\x00"];
            unmodifiedCharacters = [event.charactersIgnoringModifiers

                stringByReplacingOccurrencesOfString:@"\0"

                                          withString:@"\\x00"];
        } @catch (id exception) {
            characters = @"(exception)";
            unmodifiedCharacters = @"(exception)";
        }
        [desc appendFormat:@" keyCode=0x%d ARepeat=%d characters='%@' "
                           @"unmodifiedCharacters='%@'",
                           event.keyCode, event.ARepeat, characters,
                           unmodifiedCharacters];
        break;
    }
    case NSEventTypeLeftMouseDown:
    case NSEventTypeLeftMouseDragged:
    case NSEventTypeLeftMouseUp:
    case NSEventTypeOtherMouseDown:
    case NSEventTypeOtherMouseDragged:
    case NSEventTypeOtherMouseUp:
    case NSEventTypeRightMouseDown:
    case NSEventTypeRightMouseDragged:
    case NSEventTypeRightMouseUp:
        [desc appendFormat:@" buttonNumber=%ld clickCount=%ld",
                           event.buttonNumber, event.clickCount];
        break;
    case NSEventTypeAppKitDefined:
    case NSEventTypeSystemDefined:
    case NSEventTypeApplicationDefined:
    case NSEventTypePeriodic:
        [desc appendFormat:@" subtype=%d data1=%ld data2=%ld", event.subtype,
                           event.data1, event.data2];
        break;
    default:
        break;
    }
    return [desc copy];
}

@end
